export const READ_PROVIDER_MODELS = {
  openai: ['gpt-5-mini', 'gpt-4.1-mini', 'gpt-4o-mini', 'gpt-5', 'gpt-4.1', 'gpt-4o'],
  deepseek: ['deepseek-chat'],
  gemini: ['gemini-2.5-pro', 'gemini-2.5-flash'],
  anthropic: ['claude-sonnet-4-5', 'claude-opus-4-1', 'claude-sonnet-4-0'],
  siliconflow: ['Qwen/Qwen3-Next-80B-A3B-Instruct'],
  tensdaq: ['deepseek-v3.1'],
  ai302: ['gpt-4.1-mini', 'qwen3-235b-a22b'],
  openaiCompatible: ['use-custom-model'],
  grok: ['grok-4', 'grok-3'],
  amazonBedrock: ['anthropic.claude-3-5-sonnet-20241022-v2:0', 'anthropic.claude-3-5-haiku-20241022-v1:0', 'meta.llama3-1-405b-instruct-v1:0'],
  groq: ['llama-3.3-70b-versatile', 'llama-3.1-70b-versatile', 'mixtral-8x7b-32768'],
  deepinfra: ['meta-llama/Llama-3.3-70B-Instruct', 'meta-llama/Llama-3.1-405B-Instruct'],
  mistral: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest'],
  togetherai: ['meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'],
  cohere: ['command-r-plus', 'command-r', 'command'],
  fireworks: ['accounts/fireworks/models/llama-v3p1-405b-instruct', 'accounts/fireworks/models/llama-v3p1-70b-instruct'],
  cerebras: ['llama-3.3-70b', 'llama3.1-8b'],
  replicate: ['meta/meta-llama-3.1-405b-instruct', 'meta/meta-llama-3.1-70b-instruct', 'meta/meta-llama-3.1-8b-instruct'],
  perplexity: ['sonar-pro', 'sonar'],
  vercel: ['v0-1.5-md', 'v0-1.5-lg', 'v0-1.0-md'],
  openrouter: ['deepseek/deepseek-chat-v3.1:free', 'openai/gpt-4.1-mini'],
  ollama: ['gemma3:27b', 'deepseek-v3'],
  volcengine: ['doubao-seed-1-6-251015', 'doubao-seed-1-6-lite-251015', 'doubao-seed-1-6-flash-250828'],
} as const
export const TRANSLATE_PROVIDER_MODELS = {
  openai: ['gpt-5-mini', 'gpt-4.1-mini', 'gpt-4o-mini', 'gpt-5-nano', 'gpt-4.1-nano', 'gpt-5', 'gpt-4.1', 'gpt-4o'],
  deepseek: ['deepseek-chat'],
  gemini: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash-exp'],
  anthropic: ['claude-sonnet-4-5', 'claude-opus-4-1', 'claude-sonnet-4-0', 'claude-3-7-sonnet-latest', 'claude-3-5-haiku-latest'],
  siliconflow: ['Qwen/Qwen3-Next-80B-A3B-Instruct'],
  tensdaq: ['Qwen3-30B-A3B-Instruct-2507', 'deepseek-v3.1'],
  ai302: ['gpt-4.1-mini', 'qwen3-235b-a22b'],
  openaiCompatible: ['use-custom-model'],
  grok: ['grok-3-mini', 'grok-3-mini-fast'],
  amazonBedrock: ['anthropic.claude-3-5-haiku-20241022-v1:0', 'anthropic.claude-3-haiku-20240307-v1:0', 'meta.llama3-1-70b-instruct-v1:0'],
  groq: ['llama-3.1-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
  deepinfra: ['meta-llama/Llama-3.1-70B-Instruct', 'meta-llama/Llama-3.1-8B-Instruct'],
  mistral: ['mistral-small-latest', 'mistral-medium-latest', 'mistral-large-latest'],
  togetherai: ['meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'],
  cohere: ['command-r', 'command-r-plus', 'command'],
  fireworks: ['accounts/fireworks/models/llama-v3p1-70b-instruct', 'accounts/fireworks/models/llama-v3p1-8b-instruct'],
  cerebras: ['llama3.1-8b'],
  replicate: ['meta/meta-llama-3.1-70b-instruct', 'meta/meta-llama-3.1-8b-instruct'],
  perplexity: ['sonar-pro'],
  vercel: ['v0-1.5-md', 'v0-1.0-md'],
  openrouter: ['x-ai/grok-4-fast:free', 'openai/gpt-4.1-mini'],
  ollama: ['gemma3:4b', 'llama3.2:3b'],
  volcengine: ['doubao-seed-1-6-flash-250828', 'doubao-seed-1-6-lite-251015', 'doubao-seed-1-6-251015'],
} as const
export const NON_API_TRANSLATE_PROVIDERS = ['google', 'microsoft'] as const
export const NON_API_TRANSLATE_PROVIDERS_MAP: Record<typeof NON_API_TRANSLATE_PROVIDERS[number], string> = {
  google: 'Google Translate',
  microsoft: 'Microsoft Translator',
}
export const PURE_TRANSLATE_PROVIDERS = ['google', 'microsoft', 'deeplx'] as const

export const THINKING_MODELS = ['gemini-2.5-pro'] as const
